name: Deploy

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "puma2023-1-user"
          heroku_email: ${{secrets.HEROKU_USER_EMAIL}}